services:
    eztags.controller.tag_view:
        class: Netgen\TagsBundle\Controller\TagViewController
        parent: ezpublish.controller.base

    eztags.routing.tag_url_generator:
        class: Netgen\TagsBundle\Routing\Generator\TagUrlGenerator
        parent: ezpublish.url_generator.base
        arguments:
            - "@eztags.api.service.tags"
            - "@router.default"
            - "@ezpublish.config.resolver"

    eztags.routing.tag_router:
        class: Netgen\TagsBundle\Routing\TagRouter
        lazy: true
        arguments:
            - "@eztags.api.service.tags"
            - "@eztags.routing.tag_url_generator"
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - {name: router, priority: 200}

    eztags.platform_ui_navigationhub.zones.tags:
        class: "%ezsystems.platformui.navigationhub.zone.class%"
        public: false
        arguments:
            - "Tags"
            - "tags"
        tags:
            - {name: ezplatform.ui.zone}

    eztags..platformui.navigationhub.link.admin.tags:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "netgen_tags_admin_root"
            - "Tags"
            - "tags"
        calls:
            - [setRoutePrefix, ["netgen_tags"]]
        tags:
            - {name: ezplatform.ui.link}
        public: false
