tags:
    read: ~
    view: ~
    add: [Tag]
    addsynonym: ~
    edit: ~
    editsynonym: ~
    delete: ~
    deletesynonym: ~
    makesynonym: ~
    merge: ~
    hide: ~
    reveal: ~
    hidesynonym: ~
    revealsynonym: ~
